version: '{build}'
os: Visual Studio 2015
configuration: Release
platform: Any CPU
skip_tags: true
before_build:
- ps: >-
    nuget restore
build:
  verbosity: minimal
after_build:
- ps: >-
    $artifacts = "Binaries\Ched"

    New-Item -Type directory $artifacts

    Get-ChildItem **\bin\$env:CONFIGURATION\* -Recurse -Include *.exe, *.dll, *.config | Copy-Item -Destination $artifacts

    $shell = New-Object -ComObject("WScript.Shell")

    $wiki = $shell.CreateShortcut("$env:APPVEYOR_BUILD_FOLDER\$artifacts\Ched Wiki.url")

    $wiki.TargetPath = "https://github.com/paralleltree/Ched/wiki"

    $wiki.Save()
artifacts:
- path: Binaries
  name: Ched
deploy:
- provider: GitHub
  release: Ched
  auth_token:
    secure: KkbkUfg5iFaqdqxRAHRvPZv5+nfF99DyufxN6IijxL2TWoV3QTdkAkrnyNvIPt9+
  artifact: Ched
  draft: true
  on:
    branch: master
cache:
- packages -> **\packages.config
